CONTROL_CATALOG = [
    {
        "id": "gdpr-article-5", "framework": "GDPR", "reference": "Article 5",
        "title": "Principles relating to processing of personal data",
        "why": "Ensures data is processed lawfully, fairly, transparently, and only for defined purposes.",
        "technical_measures": ["Data minimization", "Retention rules", "Data classification", "Access restrictions"],
        "organizational_measures": ["Privacy notice", "Processing register", "Retention policy"],
    },
    {
        "id": "gdpr-article-25", "framework": "GDPR", "reference": "Article 25",
        "title": "Data protection by design and by default",
        "why": "Builds privacy safeguards into systems and defaults before release.",
        "technical_measures": ["Privacy-safe defaults", "Pseudonymization", "Field-level access", "Data masking"],
        "organizational_measures": ["Architecture review", "Privacy design review"],
    },
    {
        "id": "gdpr-article-28", "framework": "GDPR", "reference": "Article 28",
        "title": "Processor",
        "why": "Ensures third parties processing personal data are governed appropriately.",
        "technical_measures": ["Secure data exchange", "Access restrictions"],
        "organizational_measures": ["Processor register", "Data processing agreement", "Supplier review"],
    },
    {
        "id": "gdpr-article-32", "framework": "GDPR", "reference": "Article 32",
        "title": "Security of processing",
        "why": "Protects confidentiality, integrity, availability, and resilience of personal-data processing.",
        "technical_measures": ["Encryption", "MFA", "Least privilege", "Logging", "Segmentation", "DLP", "PAM"],
        "organizational_measures": ["Access reviews", "Incident process", "Security awareness"],
    },
    {
        "id": "iso-a-5-34", "framework": "ISO/IEC 27001:2022", "reference": "A.5.34",
        "title": "Privacy and protection of PII",
        "why": "Helps identify and meet obligations for privacy and PII protection.",
        "technical_measures": ["PII classification", "Privacy-aware access controls"],
        "organizational_measures": ["Privacy policy", "Control ownership", "Compliance reviews"],
    },
    {
        "id": "iso-a-5-15", "framework": "ISO/IEC 27001:2022", "reference": "A.5.15",
        "title": "Access control",
        "why": "Ensures access to information and associated assets is controlled according to business and security requirements.",
        "technical_measures": ["MFA", "Least privilege", "Role-based access control", "Privileged access management"],
        "organizational_measures": ["Access control policy", "Access reviews", "Joiner-mover-leaver process"],
    },
    {
        "id": "iso-a-8-10", "framework": "ISO/IEC 27001:2022", "reference": "A.8.10",
        "title": "Information deletion",
        "why": "Ensures information is deleted when no longer required.",
        "technical_measures": ["Deletion workflows", "Retention automation"],
        "organizational_measures": ["Retention schedule", "Deletion approvals"],
    },
    {
        "id": "iso-a-8-12", "framework": "ISO/IEC 27001:2022", "reference": "A.8.12",
        "title": "Data leakage prevention",
        "why": "Reduces the chance that sensitive data leaves approved channels.",
        "technical_measures": ["DLP policies", "Labeling", "Email controls", "Cloud monitoring"],
        "organizational_measures": ["DLP policy", "Exception approvals"],
    },
    {
        "id": "iso-a-8-15", "framework": "ISO/IEC 27001:2022", "reference": "A.8.15",
        "title": "Logging",
        "why": "Creates traceability for security-relevant events and investigation.",
        "technical_measures": ["Central logging", "Alerting", "Time synchronization"],
        "organizational_measures": ["Log review procedure", "Retention standard"],
    },
    {
        "id": "iso-a-8-24", "framework": "ISO/IEC 27001:2022", "reference": "A.8.24",
        "title": "Use of cryptography",
        "why": "Protects sensitive data using appropriate cryptographic controls.",
        "technical_measures": ["Encryption at rest", "TLS", "Key management"],
        "organizational_measures": ["Cryptography standard", "Key ownership"],
    },
]
